config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get "up" => "rails/health#show", as: :rails_health_check

  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  root "projects#index"

  resources :projects, only: %i[index show] do
    resource :comments, controller: :project_comments, only: %i[create]

    member do 
      post :update_status
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/project.rb
class Project < ApplicationRecord
  STATUSES = %i[not_started in_progress pending_completion completed].freeze
  STATUS_ENUM = STATUSES.each_with_object({}) { |status, hash| hash[status] = status.to_s }.freeze

  enum :status, STATUS_ENUM

  has_many :comments, -> { order(created_at: :desc) }, class_name: :ProjectComment
  has_many :status_changes, -> { order(created_at: :desc) }, class_name: :ProjectStatusChange

  has_and_belongs_to_many :users
end

app/models/project_comment.rb
class ProjectComment < ApplicationRecord
  belongs_to :project
  belongs_to :user

  validates :content, presence: true
end

app/models/project_status_change.rb
class ProjectStatusChange < ApplicationRecord
  enum :current_status, Project::STATUS_ENUM, instance_methods: false
  enum :previous_status, Project::STATUS_ENUM, instance_method: false

  belongs_to :project
  belongs_to :user

  validates :project, presence: true
  validates :user, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :rememberable, :validatable

  ROLES = %i[solicitor agent client].freeze
  ROLES_ENUM = ROLES.each_with_object({}) { |status, hash| hash[status] = status.to_s }.freeze
  
  enum :role, ROLES_ENUM

  has_and_belongs_to_many :projects

  def solicitor?
    role == 'solicitor'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  before_action :set_current_user, if: -> { current_user }

  private

  def set_current_user
    Current.user = current_user
  end
end

app/controllers/project_comments_controller.rb
class ProjectCommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :load_users_project, only: %i[create]

  def create
    @comment = ProjectComment.new(comment_params)
    @comment.user = current_user
    @comment.project = @project
    @comment.save

    respond_to do |format|
      format.turbo_stream
    end
  end

  protected

  def comment_params
    params.require(:project_comment).permit(:content)
  end

  def load_users_project
    @project = current_user.projects.find(params[:project_id])
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!
  before_action :load_users_project, only: %i[show update_status]

  def index
    @projects = current_user.projects
  end

  def show
    @timeline = ProjectTimeline.new(@project)
  end

  def update_status
    command = UpdateProjectStatus.call(
      project: @project,
      new_status: project_params[:status],
      user: current_user
    )

    @status_change = command.status_change

    respond_to do |format|
      format.turbo_stream
    end
  end

  protected

  def load_users_project
    @project = current_user.projects.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:status)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.slim
doctype html
html.h-full.bg-gray-100
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title= content_for(:title) || "Projects"
    meta content="width=device-width,initial-scale=1" name="viewport" /
    meta content="yes" name="apple-mobile-web-app-capable" /
    = csrf_meta_tags
    = csp_meta_tag
    = yield :head
    link href="/manifest.json" rel="manifest" /
    link href="/icon.png" rel="icon" type="image/png" /
    link href="/icon.svg" rel="icon" type="image/svg+xml" /
    link href="/icon.png" rel="apple-touch-icon" /
    = stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload"
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_importmap_tags
    = turbo_refreshes_with method: :morph, scroll: :preserve
  body.h-full
    .min-h-full
      nav.bg-gray-800
        .mx-auto.max-w-7xl.px-4.sm:px-6.lg:px-8
          .flex.h-16.items-center.justify-between
            .flex.items-center
              .flex-shrink-0
                img.h-8.w-8 alt="Homey" src="https://tailwindui.com/img/logos/mark.svg?color=indigo&shade=500" /
              .hidden.md:block
                .ml-10.flex.items-baseline.space-x-4
                  = link_to "Projects", projects_path, class: "bg-gray-900 text-white rounded-md px-3 py-2 text-sm font-medium"
            .hidden.md:block
              .ml-4.flex.items-center.md:ml-6
                - if user_signed_in?
                  span.text-gray-300.mr-4= current_user.email
                  = button_to "Logout", destroy_user_session_path, method: :delete, class: "rounded-md bg-gray-700 px-3 py-2 text-sm font-medium text-white hover:bg-gray-600"
                - else
                  = link_to "Login", new_user_session_path, class: "rounded-md bg-gray-700 px-3 py-2 text-sm font-medium text-white hover:bg-gray-600"
      main
        .mx-auto.max-w-7xl.py-6.sm:px-6.lg:px-8
          = yield

app/views/project_comments/create.turbo_stream.slim
- if @comment.valid? && @comment.persisted?
  = turbo_stream.prepend('project-timeline', partial: 'projects/comment', locals: { comment: @comment })
  - @comment = ProjectComment.new
= turbo_stream.update('project-quick-update-form', partial: 'projects/quick_update_form')

app/views/projects/_comment.html.slim
.timeline-item.border.border-gray-300.rounded-md.mb-4
  .timeline-header.bg-gray-100.px-4.py-2.flex.justify-between.items-center.border-b.border-gray-300
    .user-info.text-sm.text-gray-600
      strong.font-medium= comment.user.email
      span.text-gray-500
        |  commented 
        = time_ago_in_words(comment.created_at)
        |  ago
    = render 'projects/timeline_item_timestamp', timestamp: comment.created_at
  .timeline-content.px-4.py-3.text-sm.text-gray-700
    = simple_format(comment.content)

app/views/projects/_header.html.slim
h1#project-header.text-lg.leading-6.font-medium.text-gray-900.mb-4
  = @project.name
  |  (
  = @project.status.titleize
  | )

app/views/projects/_quick_update_form.html.slim
= render QuickUpdateProjectStatusComponent.new(@project)

- @comment ||= ProjectComment.new
= form_for [@project, @comment], url: project_comments_path(@project), class: 'mt-5', data: { controller: 'comment', turbo: true } do |f|
  .w-full.sm:max-w-lg
    = f.text_area :content, class: 'shadow-sm focus:ring-indigo-500 focus:border-indigo-500 block w-full sm:text-sm border-gray-300 rounded-md h-20 md:h-22 lg:h-32 min-h-[3rem] max-h-32', placeholder: 'Add a comment...'
  .mt-3.text-left.w-full.sm:max-w-lg
    - if @comment.errors.any?
      .form-errors= @comment.errors.full_messages.join(', ')
    = f.submit 'Post Comment', class: 'inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-md shadow-sm text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500'

app/views/projects/_status_change.html.slim
.timeline-item.border.border-gray-300.rounded-md.mb-4
  .timeline-header.bg-gray-100.px-4.py-2.flex.justify-between.items-center.border-b.border-gray-300
    .user-info.text-sm.text-gray-600
      strong.font-medium= status_change.user.email
      span.text-gray-500
        |  updated project status 
        = time_ago_in_words(status_change.created_at)
        |  ago
    = render 'projects/timeline_item_timestamp', timestamp: status_change.created_at
  .timeline-content.px-4.py-3.text-sm.text-gray-700
    | Status changed from 
    span.font-medium = status_change.previous_status.titleize
    |  to 
    span.font-medium = status_change.current_status.titleize

app/views/projects/_timeline_item_timestamp.html.slim
.timestamp.text-sm.text-gray-500.hidden.md:flex
  = timestamp.to_formatted_s(:long_ordinal)

app/views/projects/index.html.slim
.bg-white.shadow.overflow-hidden.sm:rounded-md
  ul.divide-y.divide-gray-200 role="list"
    - @projects.each do |project|
      = link_to project_path(project), class: "block hover:bg-gray-50"
        li.px-4.py-4.sm:px-6
          .flex.items-center.justify-between
            p.text-sm.font-medium.text-indigo-600.truncate
              = project.name
            .ml-2.flex-shrink-0.flex
              p.px-2.inline-flex.text-xs.leading-5.font-semibold.rounded-full.bg-green-100.text-green-800
                = project.status.titleize
          .mt-2.sm:flex.sm:justify-between
            .sm:flex
              p.flex.items-center.text-sm.text-gray-500
                = pluralize(project.users.count, 'user')
            .mt-2.flex.items-center.text-sm.text-gray-500.sm:mt-0
              p
                | Last updated #{time_ago_in_words(project.updated_at)} ago

app/views/projects/show.html.slim
.container.mx-auto.mt-2
  = render 'header'

  .bg-white.shadow.sm:rounded-lg.pb-2
    .px-4.py-5.sm:p-6

      #project-quick-update-form
        = render 'quick_update_form'

    #project-timeline.mx-auto.max.px-6
      - @timeline.each do |item|
        - if item.is_a?(ProjectComment)
          = render 'projects/comment', comment: item
        - elsif item.is_a?(ProjectStatusChange)
          = render 'projects/status_change', status_change: item

app/views/projects/update_status.turbo_stream.slim
= turbo_stream.update('project-header', partial: 'header')
= turbo_stream.update('project-quick-update-form', partial: 'quick_update_form')
= turbo_stream.prepend('project-timeline', partial: 'status_change', locals: { status_change: @status_change })